name: First Workflow
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run build
        run: npm run build
      - name: pulbish name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [test] #wait job test to completed
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: output name
        run: echo "${{ needs.test.outputs.scrip-file }}"
      - name: Install dependency
        run: npm ci
      - name: run deploy
        run: npm run build
      - uses: actions/upload-artifact@v4 #upload artifact
        with:
          name: my-artifact
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4 #download artifact
        with:
          name: my-artifact
      - name: List Artifacts
        run: ls
      - name: notify
        run: echo "deploying ...."
      
