name: First Workflow
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [test] #wait job test to completed
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run deploy
        run: npm run build
      - name: notify
        run: echo "deploying ...."
