name: First Workflow
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [test] #wait job test to completed
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run deploy
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: notify
        run: echo "deploying ...."
      
