name: First Workflow
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependency
        run: npm ci
      - name: run build
        run: npm run build
      - name: pulbish name
        id: publish
        run: |
          SCRIPT_FILE=$(find dist/assets/*.js -type f -print -quit)
          echo "script-file=$SCRIPT_FILE" >> $GITHUB_ENV
      - name: run test
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [test] #wait job test to completed
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependency
        run: npm ci
      - name: run deploy
        run: npm run build
      - uses: actions/upload-artifact@v4 #upload artifact
        with:
          name: my-artifact
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/resuse.yaml
      
